# Generated by Django 5.0.7 on 2025-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('author', models.CharField(blank=True, max_length=140)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('style', models.CharField(blank=True, max_length=120)),
                ('description_md', models.TextField(blank=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=160)),
                ('barrio', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
        ),
    ]
