# Generated by Django 5.2.5 on 2025-08-21 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('death_year', models.SmallIntegerField(blank=True, null=True)),
                ('bio_md', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('escuela', 'Escuela'), ('museo', 'Museo'), ('universidad', 'Universidad'), ('ong', 'ONG'), ('municipio', 'Municipio'), ('otro', 'Otro')], default='escuela', max_length=20)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('website', models.URLField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('barrio', models.CharField(blank=True, max_length=120)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes_md', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bibliografica', 'Bibliográfica'), ('web', 'Web'), ('archivo', 'Archivo'), ('oral', 'Oral'), ('otro', 'Otro')], default='web', max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('author', models.CharField(blank=True, max_length=180)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=600)),
                ('editorial', models.CharField(blank=True, max_length=180)),
                ('notes_md', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description_md', models.TextField(blank=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('barrio', models.CharField(blank=True, max_length=120)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('resumen_corto', models.CharField(blank=True, max_length=350)),
                ('resumen_extenso', models.TextField(blank=True)),
                ('dato_curioso', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statues', to='statues.author')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statues', to='statues.location')),
                ('tags', models.ManyToManyField(blank=True, related_name='statues', to='statues.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('foto', 'Foto'), ('audio', 'Audio'), ('doc', 'Documento')], max_length=10)),
                ('url', models.URLField(max_length=600)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('credit', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='statues.statue')),
            ],
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=140)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referer', models.URLField(blank=True, max_length=600)),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('utm_medium', models.CharField(blank=True, max_length=80)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('geohash', models.CharField(blank=True, max_length=12)),
                ('osm_zoom', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('osm_tile_x', models.IntegerField(blank=True, null=True)),
                ('osm_tile_y', models.IntegerField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('statue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='statues.statue')),
            ],
            options={
                'indexes': [models.Index(fields=['slug', 'occurred_at'], name='statues_sca_slug_a82e09_idx'), models.Index(fields=['statue', 'occurred_at'], name='statues_sca_statue__ee5e91_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatueInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('autor', 'Autor'), ('coautor', 'Coautor'), ('editor', 'Editor'), ('curador', 'Curador'), ('credito', 'Crédito')], default='credito', max_length=20)),
                ('credit_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statues_link', to='statues.institution')),
                ('statue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions_link', to='statues.statue')),
            ],
            options={
                'unique_together': {('statue', 'institution', 'role')},
            },
        ),
        migrations.CreateModel(
            name='StatueSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cita', 'Cita'), ('bibliografia', 'Bibliografía'), ('link', 'Link'), ('documento', 'Documento')], default='cita', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statue_sources', to='statues.source')),
                ('statue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statue_sources', to='statues.statue')),
            ],
            options={
                'unique_together': {('statue', 'source')},
            },
        ),
        migrations.AddIndex(
            model_name='statue',
            index=models.Index(fields=['slug'], name='statues_sta_slug_084d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='statue',
            index=models.Index(fields=['lat', 'lng'], name='statues_sta_lat_ab9494_idx'),
        ),
        migrations.AddIndex(
            model_name='statue',
            index=models.Index(fields=['author'], name='statues_sta_author__5e582f_idx'),
        ),
        migrations.AddIndex(
            model_name='statue',
            index=models.Index(fields=['location'], name='statues_sta_locatio_382ce7_idx'),
        ),
    ]
