# Generated by Django 5.2.4 on 2025-08-21 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
