# Generated by Django 5.2.4 on 2025-08-27 21:00

import statues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0003_alter_statue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=statues.models.upload_to_medios),
        ),
        migrations.AlterField(
            model_name='media',
            name='kind',
            field=models.CharField(choices=[('foto', 'Foto'), ('audio', 'Audio'), ('doc', 'Documento')], default='foto', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
